FROM golang:1.17-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY ./ ./
RUN go build -o eldencli cmd/eldencli/main.go


FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/eldencli .
ENTRYPOINT [ "./eldencli", "serve" ]